---
language: python
python:
  - "2.7"
  - "3.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Install role dependencies
  - ansible-galaxy install --roles-path=tests/roles --role-file="requirements.yml"
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Use the role and install simplesamlphp
  - ansible-playbook tests/test.yml -i tests/inventory
  # Verify simplesamlphp is installed
  - ls -la /var/www/simplesamlphp/config/config.php

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
